from __future__ import annotations

import shutil
import subprocess
from pathlib import Path
from typing import Any

import yaml

from llmstyler.io import read_yaml
from llmstyler.standards import artifact_version, model_card_template


def py_literal(value: Any) -> str:
    return repr(value)


def training_script(config: dict[str, Any]) -> str:
    train = config["training"]
    model = config["model"]
    dataset = config["dataset"]
    publishing = config["publishing"]
    style = config.get("style", {})
    exports = config.get("exports", {})
    gguf_methods = exports.get("gguf", {}).get("quantization_methods", ["q4_k_m"])
    onnx = exports.get("onnx", {})
    report_to = train.get("report_to", ["tensorboard", "wandb"])
    version = artifact_version(config)
    card_template = model_card_template(config, version)

    return f'''# ---
# jupyter:
#   jupytext:
#     formats: py:percent
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.19.2
#   kernelspec:
#     display_name: Python 3
#     language: python
#     name: python3
# ---

# %% [markdown]
# # {config["name"]}
#
# Generated by `llmstyler make-runbook`.

# %%
import os
import platform
import subprocess
from pathlib import Path

import torch
from unsloth import FastLanguageModel
from datasets import load_dataset
from huggingface_hub import HfApi, create_repo, login
from trl import SFTConfig, SFTTrainer

# %%
DATASET_ID = {py_literal(dataset["hub_repo_id"])}
DATASET_SPLIT = {py_literal(dataset.get("split", "train"))}
BASE_MODEL = {py_literal(model["base_model"])}
ADAPTER_REPO = {py_literal(publishing["adapter_repo"])}
MERGED_REPO = {py_literal(publishing.get("merged_repo"))}
GGUF_REPO = {py_literal(publishing.get("gguf_repo"))}
ONNX_REPO = {py_literal(publishing.get("onnx_repo"))}
ARTIFACT_VERSION = {py_literal(version)}
STYLE_SYSTEM_PROMPT = {py_literal(style.get("system_prompt", ""))}
DEFAULT_SYSTEM_PROMPT = {py_literal(model.get("default_system_prompt", ""))}
MAX_SEQ_LENGTH = {int(train.get("max_seq_length", 2048))}
OUTPUT_DIR = Path({py_literal(train.get("output_dir", "outputs/model"))})
GGUF_QUANTIZATION_METHODS = {py_literal(gguf_methods)}
RUN_NAME = {py_literal(train.get("run_name", config["id"]))}
MODEL_CARD_TEMPLATE = {py_literal(card_template)}

# %%
assert torch.cuda.is_available(), "CUDA is required. Run this notebook with Runbook GPU resources."
print(f"Python: {{platform.python_version()}}")
print(f"PyTorch: {{torch.__version__}}")
print(f"CUDA build: {{torch.version.cuda}}")
print(f"GPU: {{torch.cuda.get_device_name(0)}}")

hf_token = os.environ.get("HF_TOKEN") or os.environ.get("HUGGING_FACE_HUB_TOKEN") or os.environ.get("HF_HUB_TOKEN")
assert hf_token, "HF_TOKEN is required for publishing."
os.environ["HF_HUB_ENABLE_HF_TRANSFER"] = "1"
os.environ.setdefault("TOKENIZERS_PARALLELISM", "false")

if os.environ.get("WANDB_API_KEY"):
    os.environ.setdefault("WANDB_PROJECT", {py_literal(train.get("wandb_project", "llmstyler"))})
    os.environ.setdefault("WANDB_WATCH", "false")
    os.environ.setdefault("WANDB_LOG_MODEL", "false")

login(token=hf_token)
api = HfApi(token=hf_token)
print("Authenticated to Hugging Face.")


def metrics_markdown(train_metrics=None, eval_metrics=None):
    sections = []
    if train_metrics:
        sections.append("### Train")
        sections.append("")
        sections.append("| Metric | Value |")
        sections.append("| --- | --- |")
        for key, value in sorted(train_metrics.items()):
            sections.append("| " + str(key) + " | " + str(value) + " |")
        sections.append("")
    if eval_metrics:
        sections.append("### Evaluation")
        sections.append("")
        sections.append("| Metric | Value |")
        sections.append("| --- | --- |")
        for key, value in sorted(eval_metrics.items()):
            sections.append("| " + str(key) + " | " + str(value) + " |")
        sections.append("")
    if not sections:
        return "Metrics were not available when this card was written."
    return "\\n".join(sections).strip()


def write_model_card(repo_id, artifact_kind, path, metrics):
    if not repo_id:
        return None
    card = (
        MODEL_CARD_TEMPLATE.replace("__REPO_ID__", repo_id)
        .replace("__ARTIFACT_KIND__", artifact_kind)
        .replace(
            "__METRICS_SECTION__",
            metrics_markdown(metrics.get("train"), metrics.get("eval")),
        )
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(card + "\\n", encoding="utf-8")
    return path


def upload_model_card(repo_id, card_path):
    if not repo_id or card_path is None:
        return
    api.upload_file(
        repo_id=repo_id,
        repo_type="model",
        path_or_fileobj=str(card_path),
        path_in_repo="README.md",
        commit_message="Update llmstyler model card",
    )

# %%
raw_dataset = load_dataset(DATASET_ID, split=DATASET_SPLIT)
if {py_literal(dataset.get("restyled_only", False))}:
    style_id = {py_literal(style.get("id"))}
    raw_dataset = raw_dataset.filter(lambda row: row.get("restyled_style") == style_id)
MAX_SAMPLES = {py_literal(dataset.get("max_samples"))}
if MAX_SAMPLES:
    raw_dataset = raw_dataset.shuffle(seed={int(train.get("seed", 3407))}).select(range(min(int(MAX_SAMPLES), len(raw_dataset))))
print(raw_dataset)

# %%
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=BASE_MODEL,
    max_seq_length=MAX_SEQ_LENGTH,
    dtype=None,
    load_in_4bit={bool(model.get("load_in_4bit", True))},
    token=hf_token,
)

if STYLE_SYSTEM_PROMPT and DEFAULT_SYSTEM_PROMPT and tokenizer.chat_template and DEFAULT_SYSTEM_PROMPT in tokenizer.chat_template:
    tokenizer.chat_template = tokenizer.chat_template.replace(DEFAULT_SYSTEM_PROMPT, STYLE_SYSTEM_PROMPT)
    print("Replaced default chat-template system prompt with style prompt.")

model = FastLanguageModel.get_peft_model(
    model,
    r={int(train.get("lora_r", 16))},
    target_modules={py_literal(train.get("target_modules", ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]))},
    lora_alpha={int(train.get("lora_alpha", train.get("lora_r", 16)))},
    lora_dropout={float(train.get("lora_dropout", 0))},
    bias="none",
    use_gradient_checkpointing="unsloth",
    random_state={int(train.get("seed", 3407))},
)

# %%
def with_style_system(messages):
    messages = list(messages)
    if not STYLE_SYSTEM_PROMPT:
        return messages
    style_turn = {{"role": "system", "content": STYLE_SYSTEM_PROMPT}}
    if messages and messages[0].get("role") == "system":
        return [style_turn] + messages[1:]
    return [style_turn] + messages


def format_messages(batch):
    styled = [with_style_system(messages) for messages in batch["messages"]]
    texts = tokenizer.apply_chat_template(styled, tokenize=False, add_generation_prompt=False)
    if tokenizer.bos_token:
        texts = [text.removeprefix(tokenizer.bos_token) for text in texts]
    return {{"text": texts}}


dataset = raw_dataset.map(
    format_messages,
    batched=True,
    remove_columns=raw_dataset.column_names,
    desc="Applying chat template",
)

eval_fraction = {float(train.get("eval_fraction", 0.1))}
if eval_fraction and len(dataset) >= 20:
    split = dataset.train_test_split(test_size=eval_fraction, seed={int(train.get("seed", 3407))})
    train_dataset = split["train"]
    eval_dataset = split["test"]
else:
    train_dataset = dataset
    eval_dataset = None

print(f"Train rows: {{len(train_dataset)}}")
print(f"Eval rows: {{len(eval_dataset) if eval_dataset is not None else 0}}")

# %%
report_to = {py_literal(report_to)}
if "wandb" in report_to and not os.environ.get("WANDB_API_KEY"):
    report_to = [item for item in report_to if item != "wandb"]

training_args = SFTConfig(
    output_dir=str(OUTPUT_DIR),
    dataset_text_field="text",
    dataset_num_proc={int(train.get("dataset_num_proc", 4))},
    max_length=MAX_SEQ_LENGTH,
    packing={bool(train.get("packing", False))},
    per_device_train_batch_size={int(train.get("per_device_batch_size", 2))},
    gradient_accumulation_steps={int(train.get("gradient_accumulation_steps", 4))},
    warmup_ratio={float(train.get("warmup_ratio", 0.05))},
    num_train_epochs={float(train.get("num_epochs", 3))},
    learning_rate={float(train.get("learning_rate", 2e-4))},
    fp16=not torch.cuda.is_bf16_supported(),
    bf16=torch.cuda.is_bf16_supported(),
    logging_steps={int(train.get("logging_steps", 5))},
    optim={py_literal(train.get("optim", "adamw_8bit"))},
    weight_decay={float(train.get("weight_decay", 0.01))},
    lr_scheduler_type={py_literal(train.get("lr_scheduler_type", "linear"))},
    seed={int(train.get("seed", 3407))},
    report_to=report_to,
    run_name=RUN_NAME,
    eval_strategy="steps" if eval_dataset is not None else "no",
    eval_steps={int(train.get("eval_steps", 33))},
    save_strategy="steps",
    save_steps={int(train.get("save_steps", 33))},
    save_total_limit={int(train.get("save_total_limit", 2))},
    push_to_hub=True,
    hub_model_id=ADAPTER_REPO,
    hub_token=hf_token,
)

trainer = SFTTrainer(
    model=model,
    processing_class=tokenizer,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    args=training_args,
)

train_result = trainer.train()
print(train_result.metrics)
eval_metrics = None
if eval_dataset is not None:
    eval_metrics = trainer.evaluate()
    print(eval_metrics)
metrics = {{"train": train_result.metrics, "eval": eval_metrics}}

# %%
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
trainer.save_model(str(OUTPUT_DIR))
tokenizer.save_pretrained(str(OUTPUT_DIR))
adapter_card = write_model_card(ADAPTER_REPO, "QLoRA adapter", OUTPUT_DIR / "README.md", metrics)
trainer.push_to_hub(commit_message="Upload llmstyler QLoRA adapter")
upload_model_card(ADAPTER_REPO, adapter_card)
print(f"Adapter uploaded: https://huggingface.co/{{ADAPTER_REPO}}")

# %%
if MERGED_REPO:
    print("Merged model upload is deferred until after GGUF export.")

# %%
if GGUF_REPO and GGUF_QUANTIZATION_METHODS:
    create_repo(GGUF_REPO, repo_type="model", exist_ok=True, token=hf_token)
    gguf_card = write_model_card(GGUF_REPO, "GGUF export", Path("model_cards/gguf_README.md"), metrics)
    for method in GGUF_QUANTIZATION_METHODS:
        print(f"Pushing GGUF {{method}} to {{GGUF_REPO}}")
        model.push_to_hub_gguf(GGUF_REPO, tokenizer, quantization_method=method, token=hf_token)
    upload_model_card(GGUF_REPO, gguf_card)
    print(f"GGUF uploaded: https://huggingface.co/{{GGUF_REPO}}")

# %%
if MERGED_REPO:
    create_repo(MERGED_REPO, repo_type="model", exist_ok=True, token=hf_token)
    merged_card = write_model_card(MERGED_REPO, "Merged 16-bit model", Path("model_cards/merged_README.md"), metrics)
    model.push_to_hub_merged(MERGED_REPO, tokenizer=tokenizer, save_method="merged_16bit", token=hf_token)
    upload_model_card(MERGED_REPO, merged_card)
    print(f"Merged model uploaded: https://huggingface.co/{{MERGED_REPO}}")

# %%
if {bool(onnx.get("enabled", False))}:
    if not MERGED_REPO:
        raise ValueError("ONNX export requires publishing.merged_repo")
    if not ONNX_REPO:
        raise ValueError("ONNX export requires publishing.onnx_repo")
    create_repo(ONNX_REPO, repo_type="model", exist_ok=True, token=hf_token)
    onnx_dir = Path("onnx")
    subprocess.run(
        [
            "optimum-cli",
            "export",
            "onnx",
            "--model",
            MERGED_REPO,
            "--task",
            {py_literal(onnx.get("task", "text-generation-with-past"))},
            str(onnx_dir),
        ],
        check=True,
    )
    api.upload_folder(
        repo_id=ONNX_REPO,
        repo_type="model",
        folder_path=str(onnx_dir),
        commit_message="Upload llmstyler ONNX export",
    )
    onnx_card = write_model_card(ONNX_REPO, "ONNX export", Path("model_cards/onnx_README.md"), metrics)
    upload_model_card(ONNX_REPO, onnx_card)
    print(f"ONNX uploaded: https://huggingface.co/{{ONNX_REPO}}")
'''


def requirements_yaml(config: dict[str, Any]) -> dict[str, Any]:
    runtime = config.get("runbook", {}).get("runtime", {})
    packages = config.get("runbook", {}).get("packages", {})
    modal = config.get("runbook", {}).get("modal", {})
    pip_packages = list(
        packages.get(
            "pip",
            [
                "unsloth",
                "trl==0.22.2",
                "transformers==4.57.3",
                "datasets",
                "accelerate",
                "peft",
                "bitsandbytes",
                "xformers",
                "sentencepiece",
                "protobuf",
                "huggingface_hub[hf_transfer]",
                "wandb",
                "tensorboard",
                "jupytext",
                "ipykernel",
            ],
        )
    )
    if config.get("exports", {}).get("onnx", {}).get("enabled", False):
        pip_packages.extend(["optimum[onnxruntime]", "onnx", "onnxruntime"])
    return {
        "version": 1,
        "runtime": {
            "image": runtime.get("image", "pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime"),
            "gpu": runtime.get("gpu", "A10"),
            "cpu": runtime.get("cpu", 8.0),
            "memory": runtime.get("memory", 49152),
            "timeout": runtime.get("timeout", 14400),
            "kernel_name": runtime.get("kernel_name", "python3"),
            "python_version": runtime.get("python_version", "3.11"),
            "build_toolchain": runtime.get("build_toolchain", True),
            "pip_index_url": runtime.get("pip_index_url"),
            "pip_extra_index_urls": runtime.get("pip_extra_index_urls", []),
        },
        "packages": {
            "pip": pip_packages,
            "apt": packages.get(
                "apt",
                ["git", "cmake", "ninja-build", "curl", "libssl-dev", "libcurl4-openssl-dev"],
            ),
        },
        "modal": {
            "secrets": modal.get("secrets", ["wandb-secret", "huggingface-secret"]),
            "volumes": modal.get("volumes", []),
        },
        "planner": {
            "provider": "manual",
            "model": "llmstyler",
            "generated_at": None,
            "confidence": 0.8,
            "notes": ["Generated by llmstyler make-runbook."],
            "source_hash": None,
        },
    }


def runbook_command(
    config: dict[str, Any],
    notebook_path: Path,
    run_dir: Path,
    run_output: str | Path | None = None,
) -> list[str]:
    runtime = config.get("runbook", {}).get("runtime", {})
    modal = config.get("runbook", {}).get("modal", {})
    output_path = Path(run_output) if run_output is not None else run_dir / "train.ipynb"

    command = ["runbook", str(notebook_path)]
    gpu = runtime.get("gpu")
    if gpu:
        command.extend(["--gpu", str(gpu)])
    for secret in modal.get("secrets", []):
        command.extend(["--secret", str(secret)])
    timeout = runtime.get("timeout")
    if timeout:
        command.extend(["--timeout", str(timeout)])
    command.extend(["--output", str(output_path)])
    return command


def run_generated_runbook(
    config: dict[str, Any],
    notebook_path: Path,
    run_dir: Path,
    run_output: str | Path | None = None,
) -> None:
    if shutil.which("runbook") is None:
        raise RuntimeError(
            "runbook CLI is required to launch training. Install it first from "
            "https://github.com/tsilva/runbook, or rerun with --no-run to only generate "
            "the training files."
        )
    command = runbook_command(config, notebook_path, run_dir, run_output=run_output)
    print("Running " + " ".join(command))
    subprocess.run(command, check=True)


def make_runbook(
    config_path: str | Path,
    output_dir: str | Path | None = None,
    *,
    run: bool = True,
    run_output: str | Path | None = None,
) -> None:
    config = read_yaml(config_path)
    run_dir = Path(output_dir or config.get("runbook", {}).get("output_dir", f"runs/{config['id']}"))
    run_dir.mkdir(parents=True, exist_ok=True)
    notebook_path = run_dir / "train.py"
    requirements_path = run_dir / "train.py.yaml"
    notebook_path.write_text(training_script(config), encoding="utf-8")
    requirements_path.write_text(
        yaml.safe_dump(requirements_yaml(config), sort_keys=False),
        encoding="utf-8",
    )
    print(f"Wrote {notebook_path}")
    print(f"Wrote {requirements_path}")
    if run:
        run_generated_runbook(config, notebook_path, run_dir, run_output=run_output)
