from __future__ import annotations

import re
from collections.abc import Iterable
from datetime import UTC, datetime
from typing import Any

from llmstyler import __version__

DEFAULT_ARTIFACT_VERSION = "v1"


def artifact_version(config: dict[str, Any]) -> str:
    value = config.get("version") or config.get("artifact_version") or DEFAULT_ARTIFACT_VERSION
    version = str(value).strip()
    if not version:
        version = DEFAULT_ARTIFACT_VERSION
    if re.fullmatch(r"\d+(?:\.\d+)*", version):
        version = f"v{version}"
    return slugify(version)


def slugify(value: Any) -> str:
    slug = str(value).strip().lower()
    slug = re.sub(r"[^a-z0-9._-]+", "-", slug)
    slug = re.sub(r"-{2,}", "-", slug)
    slug = re.sub(r"\.{2,}", ".", slug)
    slug = slug.strip(".-")
    if not slug:
        raise ValueError("artifact name cannot be empty after slug normalization")
    return slug


def versioned_slug(value: Any, version: str) -> str:
    slug = slugify(value)
    suffix = slugify(version)
    return slug if slug.endswith(f"-{suffix}") else f"{slug}-{suffix}"


def standard_repo_id(
    hub: dict[str, Any], *, fallback_name: str, version: str, required: bool = True
) -> str | None:
    repo_id = hub.get("repo_id")
    if repo_id:
        return str(repo_id)
    owner = hub.get("owner")
    if owner:
        return f"{owner}/{versioned_slug(fallback_name, version)}"
    if required:
        raise KeyError("hub.repo_id or hub.owner is required for publishing")
    return None


def now_iso() -> str:
    return datetime.now(UTC).isoformat()


def markdown_table(headers: list[str], rows: Iterable[Iterable[Any]]) -> str:
    rendered = ["| " + " | ".join(headers) + " |"]
    rendered.append("| " + " | ".join("---" for _ in headers) + " |")
    for row in rows:
        rendered.append("| " + " | ".join(_cell(value) for value in row) + " |")
    return "\n".join(rendered)


def base_mix_dataset_card(
    *,
    config: dict[str, Any],
    manifest: dict[str, Any],
    repo_id: str | None,
) -> str:
    version = str(manifest["artifact_version"])
    plan_rows = [
        [
            item["name"],
            item["split"],
            item["count"],
            "yes" if item.get("restyle", False) else "no",
        ]
        for item in config["plan"]
    ]
    bucket_rows = sorted(manifest["buckets"].items())
    return "\n".join(
        [
            "---",
            "language:",
            "- en",
            "tags:",
            "- llmstyler",
            "- supervised-fine-tuning",
            "- chat",
            "- dataset-mix",
            "- versioned-artifact",
            "pretty_name: " + _yaml_scalar(f"{config.get('name', config['id'])} {version}"),
            "---",
            "",
            f"# {config.get('name', config['id'])} {version}",
            "",
            "## Overview",
            "",
            "This is a base chat mix produced by `llmstyler build-mix`. It contains",
            "conversation rows selected from configured Hugging Face dataset splits and",
            "marks which rows should later be restyled. Rows where `restyle` is `false`",
            "are preserved as capability anchors; rows where `restyle` is `true` are",
            "the candidates for a downstream style rewrite pass.",
            "",
            "## Versioning and Naming",
            "",
            markdown_table(
                ["Field", "Value"],
                [
                    ["Artifact type", manifest["artifact_type"]],
                    ["Artifact id", manifest["artifact_id"]],
                    ["Artifact version", version],
                    ["Hub repo", repo_id or "not configured"],
                    ["Generated by", f"llmstyler {__version__}"],
                    ["Generated at", manifest["created_at"]],
                ],
            ),
            "",
            "Default standard: publish immutable dataset versions with the version suffix",
            "in the repo name, for example `owner/base-mix-name-v1`. If the sampling",
            "plan, source data, or schema changes, publish a new version instead of",
            "mutating an existing versioned dataset.",
            "",
            "## Source Data",
            "",
            markdown_table(
                ["Field", "Value"],
                [
                    ["Dataset", config["source"]["dataset_id"]],
                    ["Config", config["source"].get("config") or ""],
                    ["Seed", manifest["seed"]],
                    ["Shuffle buffer", manifest["buffer_size"]],
                ],
            ),
            "",
            "## Sampling Plan",
            "",
            markdown_table(["Bucket", "Source split", "Rows", "Restyle candidates"], plan_rows),
            "",
            "## Composition",
            "",
            markdown_table(
                ["Metric", "Value"],
                [
                    ["Total rows", manifest["total_rows"]],
                    ["Preserved capability rows", manifest["preserve_rows"]],
                    ["Rows marked for restyling", manifest["restyle_rows"]],
                ],
            ),
            "",
            markdown_table(["Bucket", "Rows"], bucket_rows),
            "",
            "## Schema",
            "",
            markdown_table(
                ["Column", "Description"],
                [
                    ["messages", "List of chat messages with `role` and `content`."],
                    ["restyle", "Boolean flag selecting rows for the style rewrite stage."],
                    ["bucket", "Logical sampling bucket from the base mix plan."],
                    ["source_dataset", "Original Hugging Face dataset id."],
                    ["source_config", "Original Hugging Face dataset config."],
                    ["source_split", "Original split sampled for the row."],
                    ["source", "Original row source if provided by the upstream dataset."],
                ],
            ),
            "",
            "## Reproduction",
            "",
            "```bash",
            f"llmstyler build-mix {manifest.get('config_path') or config['id'] + '.yaml'}",
            "```",
            "",
            "## Intended Use",
            "",
            "Use this dataset as the stable input to one or more style rewrite passes.",
            "It is intended for supervised fine-tuning experiments and should be reviewed",
            "before use in production training runs.",
            "",
            "## Limitations",
            "",
            "This dataset inherits quality, license, safety, and representativeness",
            "properties from the configured upstream source dataset. The `restyle` flag",
            "does not mean the content has already been rewritten.",
            "",
        ]
    )


def styled_dataset_card(
    *,
    config: dict[str, Any],
    manifest: dict[str, Any],
    repo_id: str | None,
) -> str:
    version = str(manifest["artifact_version"])
    style = config["style"]
    dataset = config["dataset"]
    return "\n".join(
        [
            "---",
            "language:",
            "- en",
            "tags:",
            "- llmstyler",
            "- synthetic",
            "- style-transfer",
            "- supervised-fine-tuning",
            "- versioned-artifact",
            "pretty_name: " + _yaml_scalar(f"{style['id']} Restyled Dataset {version}"),
            "---",
            "",
            f"# {style['id']} Restyled Dataset {version}",
            "",
            "## Overview",
            "",
            "This dataset is produced by `llmstyler restyle`. It preserves the base chat",
            "mix schema while replacing assistant responses only for rows selected by",
            "`restyle: true` in the base mix. The restyling prompt is configured to keep",
            "task meaning, factual content, structured outputs, and safety caveats intact",
            "while changing the speaking style.",
            "",
            "## Versioning and Naming",
            "",
            markdown_table(
                ["Field", "Value"],
                [
                    ["Artifact type", manifest["artifact_type"]],
                    ["Artifact id", manifest["artifact_id"]],
                    ["Artifact version", version],
                    ["Hub repo", repo_id or "not configured"],
                    ["Source dataset", dataset.get("hub_repo_id") or dataset.get("input_path")],
                    ["Generated by", f"llmstyler {__version__}"],
                    ["Generated at", manifest["created_at"]],
                ],
            ),
            "",
            "Default standard: publish immutable styled dataset versions with the style",
            "and version in the repo name, for example `owner/style-mix-restyled-name-v1`.",
            "If the base dataset, rewrite prompt, rewrite model, sample size, or schema",
            "changes, publish a new versioned dataset.",
            "",
            "## Restyling Configuration",
            "",
            markdown_table(
                ["Field", "Value"],
                [
                    ["Style id", style["id"]],
                    ["Rewrite model", style["model"]],
                    ["Context mode", style.get("context_mode", "latest-user")],
                    ["Temperature", style.get("temperature", 0.7)],
                    ["Max tokens", style.get("max_tokens", 4096)],
                    ["Workers", style.get("workers", 8)],
                    ["Retries", style.get("retries", 3)],
                ],
            ),
            "",
            "## Generation Summary",
            "",
            markdown_table(
                ["Metric", "Value"],
                [
                    ["Rows", manifest["rows"]],
                    ["Restyled rows", manifest["restyled_rows"]],
                    ["Assistant rewrite calls", manifest["assistant_calls"]],
                    [
                        "Estimated cost USD",
                        f"{manifest['estimated_cost']['estimated_total_cost_usd']:.6f}",
                    ],
                    ["Prompt tokens used", manifest["actual_usage"].get("prompt_tokens", 0)],
                    [
                        "Completion tokens used",
                        manifest["actual_usage"].get("completion_tokens", 0),
                    ],
                    ["Total tokens used", manifest["actual_usage"].get("total_tokens", 0)],
                ],
            ),
            "",
            "## Files",
            "",
            markdown_table(
                ["File", "Description"],
                [
                    ["train.jsonl", "Final training rows with selected assistant messages restyled."],
                    ["checkpoint.jsonl", "Per-message rewrite checkpoint for resumability."],
                    ["preview.json", "Side-by-side original/restyled assistant previews."],
                    ["manifest.json", "Machine-readable generation metadata."],
                    ["README.md", "This dataset card."],
                ],
            ),
            "",
            "## Schema",
            "",
            markdown_table(
                ["Column", "Description"],
                [
                    ["messages", "List of chat messages with `role` and `content`."],
                    ["restyle", "Original boolean row selection flag."],
                    ["bucket", "Logical sampling bucket from the base mix plan."],
                    ["restyled_by", "Rewrite model used for rows that were restyled."],
                    ["restyled_style", "Style id applied to rows that were restyled."],
                    ["source_*", "Upstream dataset provenance from the base mix."],
                ],
            ),
            "",
            "## Reproduction",
            "",
            "```bash",
            f"llmstyler restyle {manifest.get('config_path') or config['id'] + '.yaml'}",
            "```",
            "",
            "## Limitations and Review Notes",
            "",
            "The rewrite model can introduce style drift, omissions, or unwanted additions.",
            "The `preview.json` file should be reviewed before using the dataset for model",
            "training. The dataset also inherits license, safety, and quality constraints",
            "from the base mix and its upstream source data.",
            "",
        ]
    )


def model_card_template(config: dict[str, Any], version: str) -> str:
    train = config["training"]
    model = config["model"]
    dataset = config["dataset"]
    publishing = config["publishing"]
    style = config.get("style", {})
    exports = config.get("exports", {})
    gguf_methods = exports.get("gguf", {}).get("quantization_methods", [])
    return "\n".join(
        [
            "---",
            "language:",
            "- en",
            "tags:",
            "- llmstyler",
            "- qlora",
            "- unsloth",
            "- supervised-fine-tuning",
            "- chat",
            "- versioned-artifact",
            "base_model: " + _yaml_scalar(model["base_model"]),
            "datasets:",
            "- " + _yaml_scalar(dataset["hub_repo_id"]),
            "license: other",
            "---",
            "",
            f"# {config['name']} {version} - __ARTIFACT_KIND__",
            "",
            "## Overview",
            "",
            "This model artifact was generated by an `llmstyler` Runbook training job.",
            "It is part of a versioned style-tuning release. The adapter, merged model,",
            "GGUF export, and ONNX export use separate repositories so each artifact can",
            "be consumed with the tooling that expects that format.",
            "",
            "## Versioning and Naming",
            "",
            markdown_table(
                ["Field", "Value"],
                [
                    ["Artifact kind", "__ARTIFACT_KIND__"],
                    ["Artifact version", version],
                    ["Repo", "__REPO_ID__"],
                    ["Training run id", config["id"]],
                    ["Run name", train.get("run_name", config["id"])],
                    ["Generated by", f"llmstyler {__version__}"],
                ],
            ),
            "",
            "Default standard: keep each published model artifact immutable and include",
            "the version suffix in the repo name. Publish a new version when the dataset,",
            "style prompt, base model, training recipe, or export settings change.",
            "",
            "## Training Inputs",
            "",
            markdown_table(
                ["Field", "Value"],
                [
                    ["Dataset", dataset["hub_repo_id"]],
                    ["Dataset split", dataset.get("split", "train")],
                    ["Restyled only", dataset.get("restyled_only", False)],
                    ["Base model", model["base_model"]],
                    ["4-bit load", model.get("load_in_4bit", True)],
                    ["Style id", style.get("id", "")],
                ],
            ),
            "",
            "## Style System Prompt",
            "",
            "```text",
            style.get("system_prompt", ""),
            "```",
            "",
            "## Training Recipe",
            "",
            markdown_table(
                ["Setting", "Value"],
                [
                    ["Max sequence length", train.get("max_seq_length", 2048)],
                    ["Epochs", train.get("num_epochs", 3)],
                    ["Per-device batch size", train.get("per_device_batch_size", 2)],
                    ["Gradient accumulation", train.get("gradient_accumulation_steps", 4)],
                    ["Learning rate", train.get("learning_rate", 2e-4)],
                    ["Warmup ratio", train.get("warmup_ratio", 0.05)],
                    ["LoRA rank", train.get("lora_r", 16)],
                    ["LoRA alpha", train.get("lora_alpha", train.get("lora_r", 16))],
                    ["Eval fraction", train.get("eval_fraction", 0.1)],
                    ["Seed", train.get("seed", 3407)],
                    ["Report to", ", ".join(train.get("report_to", ["tensorboard", "wandb"]))],
                ],
            ),
            "",
            "## Published Artifacts",
            "",
            markdown_table(
                ["Artifact", "Repo"],
                [
                    ["QLoRA adapter", publishing["adapter_repo"]],
                    ["Merged 16-bit model", publishing.get("merged_repo") or "disabled"],
                    ["GGUF", publishing.get("gguf_repo") or "disabled"],
                    ["ONNX", publishing.get("onnx_repo") or "disabled"],
                ],
            ),
            "",
            "GGUF quantization methods: " + (", ".join(gguf_methods) if gguf_methods else "none"),
            "",
            "## Metrics",
            "",
            "__METRICS_SECTION__",
            "",
            "## Intended Use",
            "",
            "Use this artifact for style-following chat experiments and evaluation. The",
            "adapter is intended for PEFT loading with the base model. The merged model",
            "is intended for direct Transformer loading. GGUF is intended for llama.cpp",
            "compatible runtimes. ONNX is intended for ONNX Runtime compatible workflows.",
            "",
            "## Limitations",
            "",
            "The model may over-apply the target style, miss factual nuance, or reproduce",
            "limitations from the source dataset and rewrite model. Evaluate task accuracy,",
            "safety behavior, refusal behavior, and style strength before deployment.",
            "",
        ]
    )


def _cell(value: Any) -> str:
    text = "" if value is None else str(value)
    return text.replace("|", "\\|").replace("\n", "<br>")


def _yaml_scalar(value: Any) -> str:
    text = "" if value is None else str(value)
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'
